### PR TITLE
added prev/next methods

### PR DESCRIPTION
**Pull request by untitledlt**
added `prev`/`next` methods to skip track in queue

### CODE REVIEW

**Comment by untitledlt** [comment]
is it gonna be merged any time soon?

**Comment by feross** [comment]
@untitledlt Can you link to documentation that shows that QUEUE_NEXT, etc. are the correct names to use here?

**Comment by Hypnos3** [comment]
Unfortunately, I have overlooked that. I will merge it as soon as possible.

**Comment by untitledlt** [comment]
I guess it's here:
https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media.Media#queueNext
https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media.Media#queuePrev

**Comment by untitledlt** [comment]
bump

**Pull request closed without merging**
