### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by angelnu**

### CODE REVIEW

**Comment by angelnu** [comment]
This depends on #62

**Comment by thibauts** [comment]
Awesome :)

Would it be simple to add a test for basic usage without queue ?

**Comment by angelnu** [comment]
Sure, I will take your example from the README. Should we remove the code from the readme and just reference the example in the examples folder?

**Comment by angelnu** [comment]
Done.

**Comment by angelnu** [comment]
Thanks for the pull request for #62 !

As you suggested in #66 I switched the examples to use the chromecast-scanner module. I also updated the readme to reference the examples in the example folder.

**Comment by thibauts** [comment]
I see only the lib/scanner.js file removed, but not the references to it. Am I missing something ?

**Comment by angelnu** [comment]
Yes, the last commit removes examples/lib/scanner.js that I had added in a previous commit.

The consolidated [log](https://github.com/thibauts/node-castv2-client/pull/65/files) shows the consolidated pull request. It shows the changes from #62 that you already integrated - this should be ignored when you merge.

**Comment by thibauts** [comment]
I still see references to ./lib/scanner.js in examples, [here](https://github.com/thibauts/node-castv2-client/blob/master/examples/basic.js#L5) and [here](https://github.com/thibauts/node-castv2-client/blob/master/examples/queue.js#L5).

**Pull request merged**
